---
- name: Enable the mongod port.
  firewalld: port={{ mongod_port }}/tcp permanent=true state=enabled immediate=true

- name: Enable mongod service
  service:
    name: rh-mongodb34-mongod
    enabled: yes
