---
- name: Create basic config file
  template:
    src: mongod.conf.j2
    dest: /etc/opt/rh/rh-mongodb34/mongod.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    - Restart mongodb


- name: Enable at boot and start mongodb
  service:
    name: rh-mongodb34-mongod
    enabled: yes
    state: started

- name: Create the file to initialize the replicaset
  template:
    src: repset_init.j2
    dest: /tmp/repset_init.js

- name: Initialize the replication set on the primary
  shell: /usr/bin/mongo /tmp/repset_init.js
  run_once: true
