---
# This Playbook runs all the common plays in the deployment
- name: Install basic yum tools
  yum: name={{ item }} state=installed
  with_items:
   - deltarpm
   - yum-cron

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install chrony for time sync
  yum: name={{ item }} state=installed
  with_items:
   - chrony

- name: Enable chrony for time sync
  service:
    name: chronyd
    state: started

- name: Install chrony for time sync
  yum: name={{ item }} state=installed
  with_items:
   - chrony

- name: Install mongodb
  yum: name={{ item }} state=installed
  with_items:
   - rh-mongodb34-mongodb-server
#- name: Create the mongod user
#  user: name=mongod comment="MongoD"
#
#- name: Create the data directory for the namenode metadata
#  file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory
#
#- name: Install the mongodb package
#  yum: name={{ item }} state=installed
#  with_items:
#   - libselinux-python
#   - mongodb-org
#   - mongodb-org-server
#   - bc
#   - python-pip
#   - ntp
#
#- name: Install the latest pymongo package
#  pip: name=pymongo state=latest use_mirrors=no
#
# Disable transparent_hugepages
- name: Disable transparent_hugepages, create the profile directory for tuned (1/3)
  file: path=/etc/tuned/no-thp state=directory

- name: Copy the tuned.conf to the new directory (2/3)
  copy: src=tuned.conf dest=/etc/tuned/no-thp

- name: Enable the new profile
  command: tuned-adm profile no-thp
