---
# This Playbook runs all the common plays in the deployment
- name: Install basic yum tools
  yum: name={{ item }} state=installed
  with_items:
   - deltarpm
   - yum-cron

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install chrony for time sync
  yum: name={{ item }} state=installed
  with_items:
   - chrony

- name: Enable chrony for time sync
  service:
    name: chronyd
    state: started

- name: Install mongodb
  yum: name={{ item }} state=installed
  with_items:
   - rh-mongodb34-mongodb-server
   - rh-mongodb34-mongo-tools

- name: Copy mongo official repo
  copy:
    src: mongodb-org-3.4.repo
    dest: /etc/yum.repos.d/mongodb-org-3.4.repo
    owner: root
    group: root

- name: Install mongo-shell from official repo
  yum:
    name: mongodb-org-shell
    state: installed 

# Disable transparent_hugepages
- name: Disable transparent_hugepages, create the profile directory for tuned (1/3)
  file: path=/etc/tuned/no-thp state=directory

- name: Copy the tuned.conf to the new directory (2/3)
  copy: src=tuned.conf dest=/etc/tuned/no-thp

- name: Enable the new profile
  command: tuned-adm profile no-thp
