---
# Setup as an arbiter
- name: Create the file to add the current node as an arbiter
  template: src=repset_addArbiter.j2 dest=/tmp/repset_addArbiter.j2

- name: Add the current node as an arbiter
  shell: /usr/bin/mongo -host {{ hostvars[groups["mongod_primary"][0]]["ansible_default_ipv4"]["address"] }}:{{ hostvars[groups["mongod_primary"][0]]["mongod_port"] }} /tmp/repset_addArbiter.j2
  args:
    creates: addArbiterToReplicaset
